apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: infinispan-server
  labels:
    app: infinispan-server
spec:
  replicas: 1
  serviceName: infinispan-server-headless
  selector:
    matchLabels:
      app: infinispan-server
  template:
    metadata:
      labels:
        app: infinispan-server
      name: infinispan-server
    spec:
      serviceAccountName: infinispan
      initContainers:
        - name: copy-config
          image: busybox
          command: ["sh", "-c", "cp /config-ro/cloud-keycloak.xml /config/cloud-keycloak.xml ; chown 1000 /config/* ; chmod g+w /config/*"]
          volumeMounts:
            - name: configtmp
              mountPath: "/config"
            - name: cloud-xml
              mountPath: /config-ro/cloud-keycloak.xml
              subPath: cloud-keycloak.xml
      containers:
      - args:
        - cloud-keycloak
        - -Djboss.default.jgroups.stack=kubernetes
        env:
        - name: KUBERNETES_LABELS
          value: app=infinispan-server
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              key: application-user
              name: infinispan-credentials
        - name: APP_PASS
          valueFrom:
            secretKeyRef:
              key: application-password
              name: infinispan-credentials
        - name: MGMT_USER
          value: admin
        - name: MGMT_PASS
          value: admin
        image: jboss/infinispan-server:9.3.1.Final
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/is_running.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 80
        name: infinispan-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9990
          name: management
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        - containerPort: 11222
          name: hotrod
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/is_healthy.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 80
        resources:
          requests:
            cpu: "0.2"
            memory: 512Mi
          # limits:
          #   cpu: "1"
          #   memory: 2Gi
        volumeMounts:
          - name: configtmp
            mountPath: /opt/jboss/infinispan-server/standalone/configuration/cloud-keycloak.xml
            subPath: cloud-keycloak.xml
      terminationGracePeriodSeconds: 120
      volumes:
        - name: cloud-xml
          configMap:
            name: cloud-xml
        - name: configtmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Hot Rod's port.
  labels:
    app: infinispan-server
  name: infinispan-server-hotrod
spec:
  ports:
  - port: 11222
    targetPort: 11222
  selector:
    app: infinispan-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's HTTP port.
  labels:
    app: infinispan-server
  name: infinispan-server-http
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: infinispan-server
---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-server-headless
  labels:
    app: infinispan-server
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - port: 11222
      targetPort: 11222
      protocol: TCP
      name: hotrod
  selector:
    app: infinispan-server
