apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        env:      
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: JAVA_OPTS
            value: >-
              -server
              -Djava.net.preferIPv4Stack=true
              -Djava.awt.headless=true
              -Djboss.default.jgroups.stack=kubernetes
              -Djboss.node.name=$(POD_NAME)
              -Djboss.tx.node.id=$(POD_NAME)
              -Djboss.site.name=$(KUBERNETES_NAMESPACE)
              -Dremote.cache.host=infinispan-server-hotrod
              -Dkeycloak.connectionsInfinispan.hotrodProtocolVersion=2.8
        volumeMounts:
        - name: remote-infinispan
          subPath: remote-infinispan.cli
          mountPath: /opt/jboss/startup-scripts/remote-infinispan.cli
      volumes:
      - name: remote-infinispan
        configMap:
          name: remote-infinispan